### ISSUE TITLE
Console Error with Type Command 

### ISSUE THREAD

**Issue by helptiger** [ConnorLinfoot/CratesPlus#138]
I've tested a config with Type: Command. Command is fired correctly, but I get always a console error. (Latest Spigot 1.9 with Snapshot 18)

[12:29:02 WARN]: Unknown CommandBlock failed to handle command
java.lang.IllegalStateException: Asynchronous entity add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.World.addEntity(World.java:940) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.World.addEntity(World.java:936) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.WorldServer.addEntity(WorldServer.java:1073) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.EntityHuman.a(EntityHuman.java:590) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.EntityHuman.a(EntityHuman.java:575) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.EntityHuman.drop(EntityHuman.java:513) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at net.minecraft.server.v1_9_R1.CommandGive.execute(SourceFile:75) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:580) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at plus.crates.Winning.runWin(Winning.java:189) [CratesPlus-4.0.0-SNAPSHOT-18.jar:?]
	at plus.crates.Events.CrateOpenEvent$1.run(CrateOpenEvent.java:160) [CratesPlus-4.0.0-SNAPSHOT-18.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by ConnorLinfoot** [comment]
Please post error log on Pastebin and also post config file.
