### ISSUE TITLE
Console Startup Error

### ISSUE THREAD

**Issue by Fanz2003** [ConnorLinfoot/CratesPlus#210]
Console error when I start my server up!

[23:23:41 ERROR]: Error occurred while enabling CratesPlus v4.0.0 (Is it up to date?)
java.lang.NullPointerException
at org.bukkit.Location.getBlock(Location.java:87) ~[Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:541) ~[?:?]
at plus.crates.CratesPlus.onEnable(CratesPlus.java:136) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [Spigot.jar:git-Spigot-2038f4a-cd36f6f]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

Plugins:
aAntiSpam
Auctions-2.4.2
Banknotes
BarAPI
ChatColor
ChatControl
ChestCommands
Clearlag
**CratesPlus-4.0.0**
DropParty
EffectsGUI
EnjinMinecraftPlugin
EssentialsX
EssentialsXAntiBuild
EssentialsXChat
EssentialsXProtect
EssentialsXSpawn
Factions
GAListener
HealthBar
HolographicDisplays
LapisFiller
Lockette
MassiveCore
MultiCommand
Multiverse-Core
ProtocolLib
SetSpawn
TitleAPI
Trading
Vualt
Votifier
WildTP
WorldBorder
worldedit-bukkit
worldguard

Version:
4.0.0

config.yml:
http://pastebin.com/s3G5skN3

data.yml:
http://pastebin.com/6GULvPsA

Suggestions:
A option to have no GUI (Less server and player lag!)

**Comment by ConnorLinfoot** [comment]
Please upgrade to the latest CratesPlus. The error caused is because of a location in your data.yml which no longer exists, you can either delete your data.yml or remove the location causing the issue.

Also your suggestion already exists.
