### ISSUE TITLE
Error with Holographic Displays and Crates Plus

### ISSUE THREAD

**Issue by Fyriboo** [ConnorLinfoot/CratesPlus#211]
**Please use one of the issue templates below. Issues not using the templates will likely be closed!**

# Crash, Stacktrace or Configuration issue

### Link/paste of stack trace

 [15:10:27 ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.getWatcherObject(WrappedWatchableObject.java:72) ~[ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.getIndex(WrappedWatchableObject.java:80) ~[ProtocolLib.jar:4.0.1-b291]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.pre1_9.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:156) ~[HolographicDisplays.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.1-b291]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.1-b291]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.aufdemrand.denizen.utilities.packets.intercept.DenizenNetworkManager.handle(DenizenNetworkManager.java:69) [denizen-0.9.7-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.sendPacket(AbstractListenerPlayIn.java:75) [denizen-0.9.7-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:332) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:249) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:262) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[15:10:27 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayOutEntityMetadata@6643b6f8[
    a=138
    b=[net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@408311b3, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@7723aa35, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@6c99a42d, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@7efa5b0d, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@262cc3e8, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@4cb4b71a, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@6dadda6d, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@41a3c6e6, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@1d07eb9, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@68b515fe, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@6bc8d437, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@3403bb5e, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@36a42ed1, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@767ec71e, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@5b3acc8a, net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@72ca55f8]
  ]
 

###All new Versions of HD and CratesPlus

Error happening

**Comment by ConnorLinfoot** [comment]
The error is nothing to do with CratesPlus but is solely a Holographic Displays error.

**Comment by Fyriboo** [comment]
Ok so everybody has this error? It doesn't change anything ingame just spams the console.

**Comment by ConnorLinfoot** [comment]
Works fine for myself, it'll be either another plugin or your Bukkit/Spigot version. What Bukkit/Spigot version are you using?

**Comment by Fyriboo** [comment]
1.8.8 Spigot with newest HD and CratesPlus? Do I have to downgrade HD?

**Comment by ConnorLinfoot** [comment]
You could try and see what happens, otherwise you'll need to post an issue on the HD GitHub

**Comment by Fyriboo** [comment]
I saw you also do freelancer projects and help servers. Do you have some spare time or can I get in touch with you via TeamSpeak or Skype?

**Comment by Fyriboo** [comment]
@ConnorLinfoot ? Is it possible to get in touch with you via VoiceChat?

**Comment by ConnorLinfoot** [comment]
@Fyriboo I'm not really available at the moment as I have a lot going on.
