### ISSUE TITLE
Config Error? or NullPointerException error

### ISSUE THREAD

**Issue by dudemanmax49** [ConnorLinfoot/CratesPlus#244]
so I was editing the CratesPlus config and I got an error I've never seen before and I couldn't find online. The actual developer of the plugin is unreachable atm so I thought i'd post it here. I'm no coder so I'm not sure what the errors mean.

Errors:

(PluginError)

`Error occurred while enabling CratesPlus v4.1.1 (Is it up to date?)
java.lang.NullPointerException
    at plus.crates.Winning.<init>(Winning.java:128) ~[?:?]
    at plus.crates.Crate.<init>(Crate.java:69) ~[?:?]
    at plus.crates.Handlers.ConfigHandler.<init>(ConfigHandler.java:42) ~[?:?]
    at plus.crates.CratesPlus.onEnable(CratesPlus.java:135) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:407) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:240) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:510) [craftbukkit.jar:git-Bukkit-4e19de1]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]`

Im also getting this error from the Opener but im assuming that it is just from the main plugin error:

`Error occurred while enabling CSGO-CratesPlus v1.0 (Is it up to date?)
java.lang.NullPointerException
    at plus.crates.csgo.CSGO.onEnable(CSGO.java:9) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit.jar:git-Bukkit-4e19de1]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:407) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:240) [craftbukkit.jar:git-Bukkit-4e19de1]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:510) [craftbukkit.jar:git-Bukkit-4e19de1]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]`

Here is my config:

http://pastebin.com/QsqKPHcp

I am completely dumbfounded so any help would be great. Thanks!

**Comment by ConnorLinfoot** [comment]
C'mon man, I asked you to post on Github so you would follow the format and you can't even do that..

Your issue is your lore's, they need to be a list. See example config.
