### ISSUE TITLE
Console error when giving a key (Snapshot 11)

### ISSUE THREAD

**Issue by ShaneSik** [ConnorLinfoot/CratesPlus#27]
Sometimes when people vote they don't recieve a key, is this related to CratesPlus or VoteRoulette? Error:

[10-09 14:03:55 ] [Server] [Informatie] §b[§eiboootje§b heeft gevote voor Unknown Server op §eMinestatus§b en heeft een §eSleutelMaster§b ontvangen!]
[10-09 14:03:55 ] [Server] [Informatie] Given iboootje a crate key
[10-09 14:03:55 ] [Server] WARN Task #239328 for VoteRoulette v3.1.2 SNAPSHOT generated an exception
[10-09 14:03:55 ] [Server] [Informatie] org.bukkit.command.CommandException: Unhandled exception executing command 'crate' in plugin CratesPlus v3.1-SNAPSHOT-11
[10-09 14:03:55 ] [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
[10-09 14:03:55 ] [Server] [Informatie] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
[10-09 14:03:55 ] [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
[10-09 14:03:55 ] [Server] [Informatie] at com.mythicacraft.voteroulette.awards.AwardManager$2.run(AwardManager.java:253) ~[?:?]
[10-09 14:03:55 ] [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]
[10-09 14:03:55 ] [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot1.8.7.jar:git-Spigot-44c59bf-8f0f4ed]

As you see the votes after that one worked fine:
[10-09 14:04:09 ] [Server] [Informatie] §b[§eiboootje§b heeft gevote voor Unknown Server op §eMC-Index§b en heeft een §eSleutel§b ontvangen!]
[10-09 14:04:09 ] [Server] [Informatie] Given iboootje a crate key
[10-09 14:04:11 ] [Server] [Informatie] §b[§eiboootje§b heeft gevote voor Unknown Server op §etiptopminecraft.com§b en heeft een §eSleutel§b ontvangen!]
[10-09 14:04:11 ] [Server] [Informatie] Given iboootje a crate key
[10-09 14:04:11 ] [Server] [Informatie] §b[§eiboootje§b heeft gevote voor Unknown Server op §eSERVERPACT.NL§b en heeft een §eSleutel§b ontvangen!]
[10-09 14:04:11 ] [Server] [Informatie] Given iboootje a crate key

**Comment by ConnorLinfoot** [comment]
Not sure if it's CratesPlus or not, are you able to show me the command you are running within VoteRoulette?

**Comment by ShaneSik** [comment]
Pretty simple actually. It happened only 2 times (this morning was the second time)

Rewards:
    Sleutel:
        commands:
        - crate key %player%

**Comment by ConnorLinfoot** [comment]
Next time you get the error can you copy your latest.log file from your server onto pastebin.com or something please?

It'll make it easier to debug what's going on :)

**Comment by ShaneSik** [comment]
Uhm, sure! Will do :)

**Comment by sargis123** [comment]
Connor can you help me with my issue?
