### ISSUE TITLE
Crates becoming non-crate enderchests upon restart

### ISSUE THREAD

**Issue by AlwaysCandr** [ConnorLinfoot/CratesPlus#323]
### Link/paste of stack trace/error 

`[00:10:15] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.2.1
[00:10:16] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.2.1 (Is it up to date?)
java.lang.NullPointerException
at org.bukkit.Location.getBlock(Location.java:87) ~[craftbukkit.jar:git-Spigot-72c2605-33071ec]
at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:433) ~[?:?]
at plus.crates.CratesPlus.onEnable(CratesPlus.java:209) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-72c2605-33071ec]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [craftbukkit.jar:git-Spigot-72c2605-33071ec]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

### Debug Link
https://mcdebug.xyz/cratesplus/2895

### Actions to reproduce (if known):
No idea. Just restarting server. The crates become normal enderchests upon restarting the server. I have to replace them every time the server restarts.

**Comment by ConnorLinfoot** [comment]
Try removing your data.yml and placing the crates again. Hopefully there should be something in place to prevent this in the next update.

Let me know if that fixes it.
