### ISSUE TITLE
Could not pass event BlockBreakEvent to CratesPlus v4.2.1

### ISSUE THREAD

**Issue by idnthvn** [ConnorLinfoot/CratesPlus#325]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.

### Link/paste of stack trace/error (if any)
10.12 17:41:35 [Server] ERROR Could not pass event BlockBreakEvent to CratesPlus v4.2.1
10.12 17:41:35 [Server] INFO org.bukkit.event.EventException
10.12 17:41:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1015) [CraftEventFactory.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:89) [BlockEvent$BreakEvent.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:480) [ForgeHooks.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:321) [mx.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:183) [mx.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:742) [nh.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) [ji.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
10.12 17:41:35 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
10.12 17:41:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
10.12 17:41:35 [Server] INFO Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.ARMOR_STAND
10.12 17:41:35 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_112]
10.12 17:41:35 [Server] INFO at org.bukkit.entity.EntityType.valueOf(EntityType.java:17) ~[EntityType.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO at plus.crates.Listeners.BlockListeners.onBlockBreakLegacy(BlockListeners.java:269) ~[?:?]
10.12 17:41:35 [Server] INFO at plus.crates.Listeners.BlockListeners.onBlockBreak(BlockListeners.java:244) ~[?:?]
10.12 17:41:35 [Server] INFO at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source) ~[?:?]
10.12 17:41:35 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
10.12 17:41:35 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
10.12 17:41:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
10.12 17:41:35 [Server] INFO ... 18 more

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
___Enter your debug link from /crates debug___
https://mcdebug.xyz/cratesplus/2941
### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
Placing Blocks in the world

I have noticed that the plugin works great still, but this spams the server console and when it does, the server has a slight lag behind it.

If there is anythign else please let me know. 

I am running on Thermos 1.7.10 1617 #57 (#58 is newer but has more bugs/errors)

**Comment by idnthvn** [comment]
Version 4.2.2 Fixes this. Thank you
