### ISSUE TITLE
Please help! I edited the config and now the plugin won't load! Please help!

### ISSUE THREAD

**Issue by CodaMacroft** [ConnorLinfoot/CratesPlus#336]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you.

Console Error:
[12:11:23 ERROR]: Error occurred while enabling CratesPlus v4.2.4 (Is it up to date?)
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
        at plus.crates.Winning.<init>(Winning.java:138) ~[?:?]
        at plus.crates.Crate.<init>(Crate.java:71) ~[?:?]
        at plus.crates.Handlers.ConfigHandler.<init>(ConfigHandler.java:47) ~[?:?]
        at plus.crates.CratesPlus.onEnable(CratesPlus.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8.jar:git-Bukkit-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Debug Link
I can't get a debug link because Crates Plus won't load. I am using 1.8 Craft Buck kit and Java 7 in case you need that. On a server.pro website host. Also using, CSGO-Opener I will send you the .jar file of it.
[CratesPlusConfig.txt](https://github.com/ConnorLinfoot/CratesPlus/files/691625/CratesPlusConfig.txt)

CSGO-Opener:

[CSGO-CratesPlus-1.0.zip](https://github.com/ConnorLinfoot/CratesPlus/files/691629/CSGO-CratesPlus-1.0.zip)

### Actions to reproduce (if known):
So, it was working fine until I began editing the configuration file I will post my configuration at the bottom and you can simply re-create the issue. The plugin worked 100% fine until I edited the configuration and then it didn't load and I can't seem to figure out what I did wrong. Also, please change the %name% to %player% also, please make the /crate settings GUI be able to edit crates that have a command on them and even a way to create one with a command in-game. One last thing, please make it where you can like edit the percentage in-game and the crate TYPE and almost everything in the configuration that you can edit.

**Comment by TheSaltyPug** [comment]
Try uninstalling the CSGO crates. If that does not help, what did you edit in the config file?

**Comment by CodaMacroft** [comment]
I fixed it. Thank you for your help and response. Have a good day and thank you for reading.
