### ISSUE TITLE
Please help me with an error :)

### ISSUE THREAD

**Issue by Hexid314** [ConnorLinfoot/CratesPlus#449]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Link/paste of stack trace/error (if any)

    You can also simply just use code formatting in markdown!
___  [13:03:54 WARN]: [CratesPlus] Plugin CratesPlus v4.4.3 generated an exception while executing task 63
java.lang.NullPointerException
        at plus.crates.Utils.SpigotUpdater.runSpigot(SpigotUpdater.java:59) ~[?:?]
        at plus.crates.Utils.SpigotUpdater.<init>(SpigotUpdater.java:40) ~[?:?]
        at plus.crates.CratesPlus.checkUpdate(CratesPlus.java:357) ~[?:?]
        at plus.crates.CratesPlus.access$000(CratesPlus.java:27) ~[?:?]
        at plus.crates.CratesPlus$1.run(CratesPlus.java:240) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141] ___

### Debug Link
___ https://mcdebug.xyz/cratesplus/share/T2d8h1tXF3 ___

### Actions to reproduce (if known):
___ none ___

**Comment by Hexid314** [comment]
Please help me, i have been using your plugin since 1.7.10 and now it is at 1.11.2, reason being because 1.12 sucks, but yes please help me. Thank you so much!

**Comment by ConnorLinfoot** [comment]
You've not described any issue?
