### ISSUE TITLE
pourcentage systeme dont work and i need too reset all crate chest after restart

### ISSUE THREAD

**Issue by FyFou57** [ConnorLinfoot/CratesPlus#459]
percentage system dont work, after restart serveur i need too reset all crate box,the worst plugin crate ever

88:0
01:46:56] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.4.2
[01:46:56] [Server thread/WARN]: [CratesPlus] CratesPlus does NOT fully support Bukkit 1.7, if you have issues please report them but they may not be fixed
[01:46:56] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.4.2 (Is it up to date?)
java.lang.NullPointerException
at org.bukkit.Location.getBlock(Location.java:82) ~[kingwar.jar:git-Spigot-unknown]
at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[kingwar.jar:git-Spigot-unknown]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [kingwar.jar:git-Spigot-unknown]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [kingwar.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [kingwar.jar:git-Spigot-unknown]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [kingwar.jar:git-Spigot-unknown]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [kingwar.jar:git-Spigot-unknown]

**Comment by FyFou57** [comment]
???

**Comment by ConnorLinfoot** [comment]
Please read the issue template.
