### ISSUE TITLE
Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [ConnorLinfoot/CratesPlus#462]
### Debug Link
https://mcdebug.xyz/cratesplus/share/OiYztnajBn

### Link/paste of stack trace/error (if any)
```
> [18:06:45 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.4.3
org.bukkit.event.EventException
at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[paperspigot.jar:git-Paper-1104]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:917) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperspigot.jar:git-Paper-1104]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [paperspigot.jar:git-Paper-1104]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
```

### Actions to reproduce (if known):
Caused by: java.lang.NullPointerException

**Comment by ConnorLinfoot** [comment]
The exception shared seems to only reference PaperSpigot, is there any more to this? If not it's likely an issue more related to PaperSpigot.

**Comment by tomasmessing** [comment]
No, there is not more than this. I'm using latest 1.11.2 paper spigot.
