### ISSUE TITLE
Internal error when executing crate settings and crate reload

### ISSUE THREAD

**Issue by NervouS447** [ConnorLinfoot/CratesPlus#48]
It is only happening with these 2 commands, i am using spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar
I'm guessing it's because I'm using a snapshot build? 
[07:21:38] [Server thread/ERROR]: Error occurred while enabling CratesPlus v3.1.2 (Is it up to date?)
java.lang.NoSuchFieldError: BARRIER
	at com.connorlinfoot.cratesplus.Handlers.SettingsHandler.setupSettingsInventory(SettingsHandler.java:49) ~[?:?]
	at com.connorlinfoot.cratesplus.Handlers.SettingsHandler.<init>(SettingsHandler.java:23) ~[?:?]
	at com.connorlinfoot.cratesplus.CratesPlus.onEnable(CratesPlus.java:109) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1646]

**Comment by NervouS447** [comment]
Sorry the message isn't in a very good format, did this very late at night.

**Comment by ConnorLinfoot** [comment]
CratesPlus is not supported on anything lower than 1.8.

**Comment by NervouS447** [comment]
Okay, thanks for the quick answer.
