### ISSUE TITLE
Could not pass event PlayerInteractEvent to CratesPlus v4.4.4

### ISSUE THREAD

**Issue by PassTheMayo** [ConnorLinfoot/CratesPlus#505]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link

https://mcdebug.xyz/cratesplus/share/229myyriTw

### Link/paste of stack trace/error (if any)

```
[17:02:05 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.4.4
org.bukkit.event.EventException: null
   at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[server.jar:git-Paper-1286]
   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1286]
   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1286]
   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[server.jar:git-Paper-1286]
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[server.jar:git-Paper-1286]
   at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1286]
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
   at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [server.jar:git-Paper-1286]
   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [server.jar:git-Paper-1286]
   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
   at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:186) ~[server.jar:git-Paper-1286]
   at plus.crates.Opener.BasicGUIOpener.doReopen(BasicGUIOpener.java:134) ~[?:?]
   at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:83) ~[?:?]
   at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor304.execute(Unknown Source) ~[?:?]
   at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1286]
   ... 18 more
```

### Actions to reproduce (if known):

I don't know what produced this error, but I just tried to use the `vote` key on the voter crate, and I am getting this error in console.

**UPDATE**

I restarted the server. I then tried to use the key on the crate and it took it. While it took it, it gave me the following error: https://haste.passthemayo.space/imolijizov. Then I tried the crate again and it gave me the same error that is listed under *Link/paste of stack/trace (if any)*.

**Comment by PassTheMayo** [comment]
Issue was fixed, a friend of mine helped and did something. Not sure what tho.

**Comment by ProEfeKubic** [comment]
Please, what is the problem?, i have that problem with the new version of cratesplus

**Comment by PassTheMayo** [comment]
@ProEfeKubic It was a problem with the config. It wasn't configured right.
