### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by TwanLuttik** [ConnorLinfoot/CratesPlus#507]
running on the latest spigot version
CRATEPLUS V4.4.4

i get this message when i turn on the server or when reload the server

`[11:10:51 INFO]: [CratesPlus] Enabling CratesPlus v4.4.4
[11:10:51 ERROR]: Error occurred while enabling CratesPlus v4.4.4 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:91) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
        at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]`

**Comment by BlameXeno** [comment]
Nice format
