### ISSUE TITLE
Plugin CratesPlus v4.4.4 generated an exception while executing task 31

### ISSUE THREAD

**Issue by THEJAWTHING** [ConnorLinfoot/CratesPlus#521]
Bukkit Version: 1.12.2
config.yml https://git.io/vAYNx
data.yml https://git.io/vAYNp
messages.yml https://git.io/vAYNh
plugins.txt https://git.io/vAYNj

I need to know what this means. My server is working just fine and my crates work but whenever my server is finished loading and says done, this comes up. Also a side note, whenever I place a crate in the game and it logs it in the *data* notepad, the plugin will crash again but the crates in-game will work fine. If I delete the data notepad everything will load fine but this will still show up after the server is done.

[23:17:06 WARN]: [CratesPlus] Plugin CratesPlus v4.4.4 generated an exception while executing task 31
java.lang.NullPointerException: null
        at plus.crates.Utils.SpigotUpdater.runSpigot(SpigotUpdater.java:59) ~[?:?]
        at plus.crates.Utils.SpigotUpdater.<init>(SpigotUpdater.java:40) ~[?:?]
        at plus.crates.CratesPlus.checkUpdate(CratesPlus.java:357) ~[?:?]
        at plus.crates.CratesPlus.access$000(CratesPlus.java:27) ~[?:?]
        at plus.crates.CratesPlus$1.run(CratesPlus.java:240) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-4bd94dc-f4ca180]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-4bd94dc-f4ca180]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

When I go into the config of cratesplus and turn the update to false, the title of the thread will come up over and over but it won't show the rest after the server is done.
I have updated spigot to 1.12.2, and my cratesplus plugin is updated to 4.4.4 which are both up to date.

please get back to me asap, thank you!

**Comment by ConnorLinfoot** [comment]
This error shouldn't affect the plugin as it is only for the update checker. However the issue has been resolved and is fixed in v4.4.5 - https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-7-1-12-2.5018/
