### ISSUE TITLE
Error with config File?

### ISSUE THREAD

**Issue by SkotKeller** [ConnorLinfoot/CratesPlus#529]
Ran into this issue not sure why...
    Anyone else experience  #this?
    ERROR Cannot load plugins/CratesPlus/config.yml
    P V: 4.4.5
    MC V: 1.12.2 

https://mcdebug.xyz/cratesplus/share/eeraipT7C4_

#
[16:15:10] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.4.5
[16:15:10] [Server thread/ERROR]: Cannot load plugins/CratesPlus/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 30, column 5:
        Key:
        ^
expected <block end>, but found BlockSequenceStart
 in 'string', line 35, column 6:
         - "This is a Uni's key!"
         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:83) [CratesPlus-4.4.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 30, column 5:
        Key:
        ^
expected <block end>, but found BlockSequenceStart
 in 'string', line 35, column 6:
         - "This is a Uni's key!"
         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:571) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[custom_server.jar:git-Spigot-4bd94dc-fb414fe]
	... 17 more
[16:15:10] [Server thread/INFO]: CratesPlus Version 4.4.5

**Comment by BlameXeno** [comment]
Something is wrong with the spacing of your config.yml file. Run the file through [this](yaml-online-parser.appspot.com/) and see if you've used tabs or added to many spaces. If you get stuck just pastebin the config.yml and send it here

**Comment by SkotKeller** [comment]
https://pastebin.com/2xLGjXKB

**Comment by ConnorLinfoot** [comment]
`Uni's:` is not valid within Bukkits YAML parser. You should surround it in quotes, `"Uni's:"`
