### ISSUE TITLE
Preview not working with certain enchantments

### ISSUE THREAD

**Issue by Hawkite** [ConnorLinfoot/CratesPlus#545]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link

https://mcdebug.xyz/cratesplus/share/bLWTOPPf8m

### Link/paste of stack trace/error

```
[19:58:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CratesPlus 
v4.4.5org.bukkit.event.EventException at 
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.8-R0.1.jar:git-
Spigot-59b08be-0899683] at 
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:588) [spigotmc-1.8-R0.1.jar:git-
Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) 
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigotmc-1.8-R0.1.jar:git-Spigot-
59b08be-0899683] at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_101] at 
java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_101] at 
net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigotmc-1.8-R0.1.jar:git-
Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) 
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotmc-1.8-R0.1.jar:git-
Spigot-59b08be-0899683] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) 
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at java.lang.Thread.run(Thread.java:745) 
[?:1.7.0_101]Caused by: java.lang.NullPointerException at 
org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaItem.applyEnchantments(CraftMetaItem.java:569) ~
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaItem.applyToItem(CraftMetaItem.java:524) ~
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:404) ~
[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:48) ~[spigotmc-
1.8-R0.1.jar:git-Spigot-59b08be-0899683] at 
org.bukkit.craftbukkit.v1_8_R1.inventory.CraftInventory.setItem(CraftInventory.java:81) ~[spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] at 
plus.crates.Events.CratePreviewEvent.doEvent(CratePreviewEvent.java:52) ~[?:?] at 
plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:73) ~[?:?] at 
sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?] at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~
[?:1.7.0_101] at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_101] at 
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigotmc-1.8-
R0.1.jar:git-Spigot-59b08be-0899683] ... 17 more

```

### Actions to reproduce:
If I add a diamond chestplate with a protection 4 enchantment to a crate it will not show a left click preview (I can roll and receive the chestplate with prot 4 just fine).
If I do fire aspect instead it works just fine.

**Comment by Hawkite** [comment]
Fixed: Turns out it uses bukkit enchantment names not minecraft enchantment names
