### ISSUE TITLE
Hologram goes/percentages/startup error

### ISSUE THREAD

**Issue by howy7214** [ConnorLinfoot/CratesPlus#547]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

From version 4.3 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. Please run this and submit the share link with your issue.

### Debug Link
___Enter your debug link from `/crates debug`. Not providing this may result in the issue being closed without warning. If you are unable to use this command please provide your Bukkit version, a list of plugins and your config.yml for CratesPlus.___

Debug error
AAC v3.3.14
AdvancedPortals v0.0.35
AreaShop v2.4.0
ASkyBlock v3.0.8.2
BanManager v5.15.0
BungeeTabListPlus v2.8.3
ChestShop v3.8.12
ClearLag v2.9.7
CoreProtect v2.14.2
CratesPlus v4.4.5
CSGO-CratesPlus v1.0
EnjinMinecraftPlugin v3.4.0
Essentials v2.0.1-b547
EssentialsChat v2.15.0.1
EssentialsSpawn v2.0.1-b547
FastAsyncWorldEdit v18.04.21-13b5ded-1083-19.5.17
GriefPrevention v16.7.1
HeavySpleef v2.4.1
HideAndSeek v3.0
HolographicDisplays v2.2.6
iDisguise v5.6.4
Jobs v4.5.3
MCDiscordIntegrator v1.6.7
mcMMO v1.5.09-SNAPSHOT
MiniaturePets v1.5.4
Multiverse-Core v2.6.0-SNAPSHOT-b736
Multiverse-Inventories v1.4
MultiWorldMoney v2.2
MyCommand v5.3.4
NoFlyZone v1.3
Paintball v1.3.10
PermissionsEx v1.23.4
PlaceholderAPI v2.8.5
PlotSquared v3.5.0-SNAPSHOT-95f8aaa
PlugMan v2.1.4
ProtocolLib v4.3.0
SurvivalGames v0.6.7
TitleManager v2.0.9
UltraCosmetics v2.4.9
Vault v1.5.6-b49
ViaBackwards v2.3.1
ViaVersion v1.3.0
VoidGenerator v1.2.0
VoteParty v1.9.9.1
Votifier v2.3.6
VotingPlugin v5.12.5
Vouchers v2.1.0
Wild v3.13.0
WorldEdit v6.1.8-SNAPSHOT;cd4729f
WorldGuard v6.2.1;84bc322

### Actions to reproduce (if known):
When the server restart holograms goes, says the percentages are not 100% right when they are I double check them I have a .text file with it all items with the numbers percentages I put in them in, if you want them happy to pass it to you. Also running latest Spigot as will. 

Please help Thank you

Startup error:
[01:01:00] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.4.5
[01:01:00] [Server thread/WARN]: Your percentages must NOT add up to more than 100%
[01:01:00] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.4.5 (Is it up to date?)
java.lang.NullPointerException: null
    at org.bukkit.Location.getBlock(Location.java:91) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
    at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
    at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-21d5f75]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by ConnorLinfoot** [comment]
Can you please provide your config.yml? If it's stating your percentages add up to higher than 100% they probably are.
