### ISSUE TITLE
Crates not opening and commands not working.

### ISSUE THREAD

**Issue by samwis3** [ConnorLinfoot/CratesPlus#571]
Hi, I am getting this error in my console every time I restart the server and in-game The crates do not work and neither does the /crate command.

[ERROR] Error occurred while enabling CratesPlus v5.0-SNAPSHOT-5 (Is it up to date?)

java.lang.NullPointerException: null

at plus.crates.CratesPlus.onEnable(CratesPlus.java:137) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

No idea what is causing this but it's the same when using the stable version of crates plus.

**Comment by ConnorLinfoot** [comment]
Please follow the instructions and provide more information about your server.

**Comment by samwis3** [comment]
i would have loved to do /crate debug as per the instructions but like i said you cant do any /crate command.

**Comment by samwis3** [comment]
so yeah good to know you really wanna help people that use your plugin, if all you do is say sorry can't help you cos you didn't do a command, that at the moment isn't even working.

**Comment by ConnorLinfoot** [comment]
The instructions state the command is broke and do tell you what to provide instead.

**Comment by samwis3** [comment]
I provided the error the console is coming up with in the original post. I advised you that this error happens boat with the stable and development version of the plugin. I can't supplies you with a way of replicating it as I don't know the cause since this error happens every time the server is restarted.

So please tell me what specifically you need information wise about my server to fix the plugin.

**Comment by ConnorLinfoot** [comment]
_sigh_ It literally says it when you create new issue.

`Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your 'config.yml' and provide your Bukkit version. If possible a plugin list and providing your 'data.yml' is also appreciated and may be requested if needed.`
