### ISSUE TITLE
Crates bug on loading

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [ConnorLinfoot/CratesPlus#583]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

data.yml might be helpful

`Data Version: 2
Crate Locations:
  platinum:
  - spawn|-2|145|-139
  gold:
  - spawn|-6|144|-139
  miracle:
  - spawn|2|146|-140
  elementium:
  - spawn|6|145|-139
  ethernum:
  - spawn|10|144|-139
  symbol:
  - spawn|21|146|-128
  garden:
  - spawn|21|146|-134
  build:
  - spawn|-14|145|-135
  enchanted:
  - spawn|-20|145|-131
  enchantedlite:
  - spawn|-18|145|-129
`

### Link/paste of stack trace/error (if any)

`[22:19:46] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.1 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:100) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[PaperSpigot-1.13.1-b327.jar:git-Paper-327]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

### Actions to reproduce (if known):
Just load on server

**Comment by JhonatanPereira** [comment]
Same problem here
