### ISSUE TITLE
Bug after restart

### ISSUE THREAD

**Issue by FyFou57** [ConnorLinfoot/CratesPlus#586]
### Debug Info

I do not understand, when I restart the server some box no longer works, it will remove them and put back, yet in the data file, they are good ... it produces it every time!

1.7.10 PaperSpigot 

# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V4.4.2 Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# - %rand;100;500% - Generates a random number between two numbers, example is between 100 and 500.
# ------------------------------------------
# Don't change the config version!

Config Version: 6
Update Checks: true
Update Branch: spigot
Metrics: true
Default Opener: BasicGUI
Default Cooldown: 2
Crate Protection: false
Disable Key Swapping: false
Default Hologram Text:
- '%crate%'
- Clique droit pour ouvrir
- Clique gauche pour voir
Crates:
  leg:
    Key:
      Item: KEY_LEGENDAIRE
      Name: Clé légendaire
      Enchanted: true
    Knockback: 0.0
    Broadcast: false
    Firework: false
    Preview: true
    Block: GALAXY_CHEST
    Color: WHITE
    Winnings:
      '1':
        Type: ITEM
        Item Type: GOLDEN_APPLE
        Item Data: 1
        Percentage: 3
        Name: NONE
        Amount: 5
        Enchantments: []
        Lore: []
      '2':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Item Data: 0
        Percentage: 0.1
        Commands:
        - 'spawners add pig_zombie %name%'
        Name: '&5Spawner de PIG_ZOMBIE'
        Amount: 1
        Enchantments: []
        Lore: []
      '3':
        Type: ITEM
        Item Type: OBSIDIAN_RENFORCER
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
      '4':
        Type: ITEM
        Item Type: DYNAMITE
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 16
        Enchantments: []
        Lore: []
      '5':
        Type: ITEM
        Item Type: GULZEN
        Item Data: 0
        Percentage: 3
        Name: NONE
        Amount: 4
        Enchantments: []
        Lore: []
      '6':
        Type: ITEM
        Item Type: ROYAL
        Item Data: 0
        Percentage: 2
        Name: NONE
        Amount: 3
        Enchantments: []
        Lore: []
      '7':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Item Data: 0
        Percentage: 1.5
        Name: '&5Spawner de Zombie'
        Commands:
        - 'spawners add zombie %name%'
        Amount: 1
        Enchantments: []
        Lore: []
      '8':
        Type: ITEM
        Item Type: TNT
        Item Data: 0
        Percentage: 11
        Name: NONE
        Amount: 2
        Enchantments: []
        Lore: []
      '9':
        Type: ITEM
        Item Type: XRAY
        Item Data: 0
        Percentage: 9
        Name: NONE
        Amount: 2
        Enchantments: []
        Lore: []
      '10':
        Type: ITEM
        Item Type: JAFARM
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 16
        Enchantments: []
        Lore: []
      '11':
        Type: ITEM
        Item Type: ALYRITE_SWORD
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - FIRE_ASPECT-2
        Lore: []
      '12':
        Type: ITEM
        Item Type: RUBIS_CHEST
        Item Data: 0
        Percentage: 9
        Name: NONE
        Amount: 16
        Enchantments: []
        Lore: []
      '13':
        Type: ITEM
        Item Type: GOLDEN_BREAD
        Item Data: 0
        Percentage: 7
        Name: NONE
        Amount: 5
        Enchantments: []
        Lore: []
      '14':
        Type: ITEM
        Item Type: ALIOPEARL
        Item Data: 0
        Percentage: 10
        Name: NONE
        Amount: 4
        Enchantments: []
        Lore: []
      '15':
        Type: ITEM
        Item Type: VOLATILE_DYNAMITE
        Item Data: 0
        Percentage: 8
        Name: NONE
        Amount: 64
        Enchantments: []
        Lore: []
      '16':
        Type: ITEM
        Item Type: NUCLEARYTE
        Item Data: 0
        Percentage: 4
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '17':
        Type: ITEM
        Item Type: GLACYTE
        Item Data: 0
        Percentage: 4
        Name: NONE
        Amount: 1
        Enchantments: []
        Lore: []
      '18':
        Type: COMMAND
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Percentage: 0.4
        Name: '&5x1 Clé Spawner'
        Commands:
        - crate key %name% spawner 1
        Amount: 1
        Enchantments: []
        Lore: []

**Comment by FyFou57** [comment]
I specify that everything works perfectly before a reboot

**Comment by FyFou57** [comment]
[23:29:50] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.1 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:82) ~[kingwar.jar:git-PaperSpigot-1f7d532]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[kingwar.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [kingwar.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [kingwar.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [kingwar.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [kingwar.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [kingwar.jar:git-PaperSpigot-1f7d532]
