### ISSUE TITLE
CratesPlus not opening at startup

### ISSUE THREAD

**Issue by garman1001** [ConnorLinfoot/CratesPlus#603]
`05.01 04:06:07 [Server] ERROR Error occurred while enabling CratesPlus v4.5.1 (Is it up to date?)
05.01 04:06:07 [Server] INFO java.lang.IllegalArgumentException: character to be escaped is missing
05.01 04:06:07 [Server] INFO at java.util.regex.Matcher.appendReplacement(Matcher.java:809) ~[?:1.8.0_191]
05.01 04:06:07 [Server] INFO at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_191]
05.01 04:06:07 [Server] INFO at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_191]
05.01 04:06:07 [Server] INFO at plus.crates.Crate.<init>(Crate.java:67) ~[?:?]
05.01 04:06:07 [Server] INFO at plus.crates.Handlers.ConfigHandler.<init>(ConfigHandler.java:47) ~[?:?]
05.01 04:06:07 [Server] INFO at plus.crates.CratesPlus.onEnable(CratesPlus.java:177) ~[?:?]
05.01 04:06:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
05.01 04:06:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by garman1001** [comment]
Using Spigot 1.12.2 with ViaVersion
