### ISSUE TITLE
Crates stop working on restart

### ISSUE THREAD

**Issue by j19mes** [ConnorLinfoot/CratesPlus#608]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

Due to a change in the GitHub Gist API the debug command currently doesn't work. Please can you upload your `config.yml` and provide your Bukkit version. If possible a plugin list and providing your `data.yml` is also appreciated and may be requested if needed.

Config: https://pastebin.com/NfeuRfYe
Data: https://pastebin.com/XXTMNsEX
### Link/paste of stack trace/error (if any)

`[17:50:06] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.4.4 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:91) ~[server.jar:git-Spigot-3d850ec-809c399]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-3d850ec-809c399]`

    You can also simply just use code formatting in markdown!
___We need all of the stack trace! Do not cut off parts of it.___

### Actions to reproduce (if known):
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___

None, just seems to break everytime my server restarts  i have to replace the crates & they work again, i have tried reseting the data.yml and they still disappear everytime.

**Comment by cassie-k** [comment]
Having the same issue with v4.5.2 on 1.14.2 spigot server. Not hopeful seeing this ticket has been open since January...

**Comment by j19mes** [comment]
Yeah i switched to goldencrates in the end because it was  never fixed.
