### ISSUE TITLE
[URGENT ISSUE] Dupe Glitch

### ISSUE THREAD

**Issue by flash1110** [ConnorLinfoot/CratesPlus#616]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com).

### Debug Info

Plugin List: Works with only CratesPlus installed, as well as other plugins.

### Link/paste of stack trace/error (if any)
Continious Spam of this until I log back on:
[17:49:42 WARN]: [CratesPlus] Plugin CratesPlus v4.5.1 generated an exception while executing task 58
java.lang.IllegalStateException: Asynchronous command dispatch!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[server.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:691) ~[server.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) ~[server.jar:git-Spigot-69774b3-ec2095d]
        at plus.crates.Opener.BasicGUIOpener$1.run(BasicGUIOpener.java:70) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-69774b3-ec2095d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

### Actions to reproduce (if known):
Use a key.
Log Off.
Log back on.
Use another key to open up a crate.
Click on same Crate Chest
Items start spawning out of the floor.

**Comment by SiuanSong** [comment]
Are you using an old 1.12 config?  Item names need to be updated.  I can't reproduce this following the steps you have.

**Comment by flash1110** [comment]
I can confirm we are using the newest version and the config generated by that version.
