### ISSUE TITLE
Issue with cratesplus version 4.5.2

### ISSUE THREAD

**Issue by johncsuti1234** [ConnorLinfoot/CratesPlus#648]
Please help me with this!
This is caused by opening a chest that isn't a crate!
[03:13:11 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1222) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        ... 17 more

And this when ever i try to reload the plugin in game
[03:14:09 ERROR]: Could not pass event PlayerCommandPreprocessEvent to GUIShop v7.1.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1613) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at com.pablo67340.guishop.main.Main.loadCommands(Main.java:198) ~[?:?]
        at com.pablo67340.guishop.listenable.PlayerListener.onCommand(PlayerListener.java:48) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        ... 16 more

All config files added via zip
[Files.zip](https://github.com/ConnorLinfoot/CratesPlus/files/3270978/Files.zip)

**Comment by johncsuti1234** [comment]
Also minecraft version is 1.13.2 spigot version is 1.13.2 as well

**Comment by Iwitrag** [comment]
Can confirm, lot of spam messages in console... all looks the same.

**Comment by johncsuti1234** [comment]
Okay good it’s not just me if we could figure this out it would be great

**Comment by johncsuti1234** [comment]
Removed simple plugin manager and this is what it shows now!

[21:19:28 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1222) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]   
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-1a3504a-dfa7583]
        ... 17 more

**Comment by TheMonDon** [comment]
I'm also having this issue on Paper 1.12.2

**Comment by johncsuti1234** [comment]
found the solutions to this issue

Steps to fix this
1. stop the server
2. remove the guishop.jar from your plugins folder
3. find a better plugins then this shit that the owner doesn't care about fuck you connorlinfoot
4. better plugin will have a thoughtful owner that wants the close fucking issues again fuck you connorlinfoot

**Comment by johncsuti1234** [comment]
@TheMonDon 

Yes i converted my server jar to paper 1.13.2 the issue is still there and it looks like @ConnorLinfoot doesn't help on any issues as there are 81 unresolved issues

**Comment by johncsuti1234** [comment]
yup happens with paper 1.13.2 as well @TheMonDon here is my error on paper as i just converted over

[03:14:19 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
java.lang.NullPointerException: null
        at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-631]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-631]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-631]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-631]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-631]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-631]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-631]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by johncsuti1234** [comment]
FOUND a fix for all 1.13.2 versions of mc downgrade to version 4.5.1 of crates plus it wont throw the error any more till @ConnorLinfoot can fix the 1.13.2 issue with 4.5.2

**Comment by johncsuti1234** [comment]
Or he will ignore all he has to do with this
