### ISSUE TITLE
1.14.3 issue

### ISSUE THREAD

**Issue by ToBugs** [ConnorLinfoot/CratesPlus#658]
### Debug Info

was running fine on 1.14.2 but once i up dated to 1.14.3  I get this message when a player opens a normal chest, not the crate chest

### Link/paste of stack trace/error (if any)

    Y[11:17:48] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:435) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3737.000000007810DE30.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigotmc-1.14.3-R0.1.jar:git-Spigot-595711b-e8b39d4]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: java.lang.NullPointerException

### Actions to reproduce (if known):

Maybe this will help not sure,

**Comment by alan67160** [comment]
same as me
