### ISSUE TITLE
PlayerInteractEvent to CratesPlus v4.5.2

### ISSUE THREAD

**Issue by alessiettojr** [ConnorLinfoot/CratesPlus#664]
The problems are:
1. When I do / crate settings and try to change the name of the chest it disconnects me.
2. When I do / crate settings to change the color nothing happens.
3. [ERROR] Could not pass event PlayerInteractEvent to CratesPlus v4.5.2

How can I solve these problems?

`[ERROR] Could not pass event PlayerInteractEvent to CratesPlus v4.5.2

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:435) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3332.00000000240DE0B0.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NullPointerException

at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]

at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]

... 20 more`

**Comment by milothedalmador** [comment]
Also getting this error in our console.

> [09:37:43 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2 java.lang.NullPointerException: null
