### ISSUE TITLE
Error : Could not pass event PlayerInteractEvent to CratesPlus v4.5.2

### ISSUE THREAD

**Issue by MrPungle** [ConnorLinfoot/CratesPlus#674]
`[23:30:23 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor493.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 17 more
`

Got this error :/

**Comment by TheFancepants** [comment]
I am receiving the same error.

**Comment by mrcoffee1026** [comment]
Constant spam in my console with this error as well.  Very annoying, please fix!

**Comment by CaliDreams** [comment]
Also getting this error spam to the point of lagging my server out.
1.14.4 - paper-153
CratesPlus 4.5.2

**Comment by killbots2012** [comment]
Anyone aware if it's v5.0? I also started getting the same error just recently.

**Comment by timmehz** [comment]
same issue also, I think its a bug within the current version of 4.5.2

**Comment by Steve0Jr** [comment]
I keep getting this error and when I go and do /crate create it crashes my client. 

Spigot 1.13.2 - CratesPlus 4.4.5 - 4.5.2 - All versions crash me

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: net.minecraft.server.v1_13_R2.BlockPosition cannot be cast to [Ljava.lang.String;

**Comment by Cylizion** [comment]
> `[23:30:23 ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2

All this error is doing is telling you that it couldn't tell CratesPlus that it has to read the PlayerInteractEvent, as it doesn't have to (since it's not a crate). Unless you have to read through logs (which you can skim via Ctrl+F), this shouldn't bother you.

> Constant spam in my console with this error as well. Very annoying, please fix!
> 1.14.4 - paper-153
> CratesPlus 4.5.2
> (duplicate #659)

> Also getting this error spam to the point of lagging my server out.
> 1.14.4 - paper-153
> CratesPlus 4.5.2

If you have not yet gotten a fix for this, please update PaperSpigot, as it is 77 versions behind. When you posted that, PaperSpigot was actually updated to PaperMC 154, although it likely had no effect on performance.

> Anyone aware if it's v5.0? I also started getting the same error just recently.

If you're running v5.0, it may cause errors, as v5.0 is not recommended on public servers as it's a development/snapshot build.

> same issue also, I think its a bug within the current version of 4.5.2

Perhaps. However, the error does not affect gameplay in any way.

> I keep getting this error and when I go and do /crate create it crashes my client.
> 
> Spigot 1.13.2 - CratesPlus 4.4.5 - 4.5.2 - All versions crash me
> 
> Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ClassCastException: net.minecraft.server.v1_13_R2.BlockPosition cannot be cast to [Ljava.lang.String;

Although related, this may be more apt to a response as it's own issue.

**Comment by mrcoffee1026** [comment]
I'm on paper-230 now and am using the unofficial build that included pull request #678 (CratesPlus version 4.5.3) which resolved this issue... months ago.  I mean thanks for the reply but... glad I wasn't waiting on you, personally.

**Comment by Cylizion** [comment]
Hope we can get the attention of the author @MrPungle so he can close this... The PR build works for me as well.

**Comment by CreeperCry04** [comment]
Yeah, same error.
