### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by bjorno43** [ConnorLinfoot/CratesPlus#680]
### Debug Info

config.yml: [https://pastebin.com/4LJhdP7S](https://pastebin.com/4LJhdP7S)
data.yml: [https://pastebin.com/mXuCdYDW](https://pastebin.com/mXuCdYDW)

### Link/paste of stack trace/error (if any)

Full server log: [https://pastebin.com/e0iWxWQv](https://pastebin.com/e0iWxWQv)

Specific exception:
```Java
Error occurred while enabling CratesPlus v4.5.2 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:123) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
```

### Actions to reproduce (if known):
Worked perfectly fine on installation. Created and placed down a few crates. Edited their contents through the settings command. Restarted the server and the exception popped up.

### Server details ###

OS: Windows 7 64 bit
RAM: 24 Gig (12 allocated to Spigot)
Spigot: 1.14.4 (latest)

### Other plugins installed ###
- Advanced Portals
- EssentialsX
- GriefPrevention
- LuckPerms
- MineableSpawners
- Multiverse Core
- Vault
- WorldEdit

**Comment by matbcvo** [comment]
#678

**Comment by dashaw92** [comment]
#678 is unrelated to this issue.
