### ISSUE TITLE
Plugin crashes on server restart

### ISSUE THREAD

**Issue by GemcraftServer** [ConnorLinfoot/CratesPlus#696]
Plugin was working perfectly fin until my server restarted. On startup, the plugin got disabled.

[05:00:40] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.5.2
[05:00:40] [Server thread/WARN]: [CratesPlus] CratesPlus has not yet been officially tested with Bukkit 1.14.4 but should still work
[05:00:40] [Server thread/WARN]: [CratesPlus] Please let me know if there are any errors or issues
[05:00:40] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.2 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.4.jar:git-Paper-207]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-207]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-207]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-207]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-207]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-207]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-207]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[05:00:40] [Server thread/INFO]: [CratesPlus] Disabling CratesPlus v4.5.2

**Comment by CookieMellow** [comment]
bump same problem

**Comment by GemcraftServer** [comment]
@CookieMellow i'd recommend switching to CrateReloaded, it works so much better and doesnt spam the console
