### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by brnxx** [ConnorLinfoot/CratesPlus#699]
`[16:22:13] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.5.1
[16:22:13] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.1 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

![image](https://user-images.githubusercontent.com/49076883/66426401-22f9ee00-e9e8-11e9-8dbb-143975cdf956.png)

**Comment by Cylizion** [comment]
You're running a PaperSpigot Snapshot for Minecraft 1.8.8, which is an outdated version. The CratesPlus version you may want is before v4.1, as there was 1.8 compatibility added in v3.1.4
