### ISSUE TITLE
CratePLus keeps disabling

### ISSUE THREAD

**Issue by mrsbling** [ConnorLinfoot/CratesPlus#715]
I have exhausted all avenues before creating issue.

I was using Paper 225, crates Voter, VoterPLus, Christmas, and SantaElf keys and chests were working fine. Then I updated to Paper 226 no other updates were done. It worked. As of Thursday November 21 is when it literally stopped working or disabled its self. When players vote they started getting warnings (Preview 1)
7:30 WARN]: [SuperbVote] Task #291 for SuperbVote v0.5.4 generated an exception
org.bukkit.command.CommandException: Cannot execute command 'crate' in plugin CratesPlus v4.5.3 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:660) ~[patched_1.14.4.jar:git-Paper-226]
        at io.minimum.minecraft.superbvote.votes.rewards.VoteReward.runCommands(VoteReward.java:38) ~[?:?]
        at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$null$1(SuperbVoteListener.java:85) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_161]
        at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$processVote$2(SuperbVoteListener.java:85) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-226]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161

 then when they would /crate claim this error

 (preview 2)
[14:46:40 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'crates' in plugin CratesPlus v4.5.3 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-230]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-230]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-230]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-230]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

I tried to update to paper 230 thinking maybe it might work, Negative. Then I went back to Paper 225. 

I tried to re install the plugin as a new one, checked my votifier still the same

Any suggestions (1.14.4 Paper I am running)

**Comment by SiuanSong** [comment]
This plugin kept disabling for me at restarts.  I switched to another plugin because it seems to be a dying resource. :(

**Comment by Cylizion** [comment]
I have no issues on the latest Spigot version. **HOWEVER I AM RUNNING CratesPlus 4.5.2!!!** Try to downgrade to that version!

**Comment by Cylizion** [comment]
If the above doesn't solve the issue, please DM me on Discord (Cylizion#0001) and I'll do my best to help!

**Comment by mrsbling** [comment]
I sent you a friend request Cylizion
Also I am running paper 1.14.4 I hope that isn't a ;large difference. I
will search for the 4.52

**Comment by mrsbling** [comment]
I redownloaded it 4.5.2 and it did this upon voting to give the key
[14:34:51 WARN]: [SuperbVote] Task #919 for SuperbVote v0.5.4 generated an exception
org.bukkit.command.CommandException: Cannot execute command 'crate' in plugin CratesPlus v4.5.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:660) ~[patched_1.14.4.jar:git-Paper-234]
        at io.minimum.minecraft.superbvote.votes.rewards.VoteReward.runCommands(VoteReward.java:38) ~[?:?]
        at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$null$1(SuperbVoteListener.java:85) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_161]
        at io.minimum.minecraft.superbvote.votes.SuperbVoteListener.lambda$processVote$2(SuperbVoteListener.java:85) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by mrsbling** [comment]
Then when I try to use /crateplus it does an internal error and disables

4:36:02 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'cratesplus' in plugin CratesPlus v4.5.2 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Cylizion** [comment]
Please upload your `config.yml` by attaching it. I can try to help you further with that.

Also, if you can, list all plugins on the server with either a screenshot of the in-game command `/plugins` or a list.

**Comment by Cylizion** [comment]
> I sent you a friend request Cylizion

I didn't get it

**Comment by mrsbling** [comment]
[config (1).zip](https://github.com/ConnorLinfoot/CratesPlus/files/3935493/config.1.zip)

**Comment by mrsbling** [comment]
World Edit
World Guard
Votifier
Votelinks
USkyblock
SuperbVote
Sleepmost
Random Telport
Paintball
Mydriad Clans
Multiverse Inventories
Multiverse Core
LuckPerms
Holographic Displays
Herochat
GiveSpawner
EssentialsGeo
EssentialsX
Enjin
Duties
Domain
CratePlus
CoreProtect
ClearFlora
ChristmasPLus
BannerBoards
AutoMessage
AdvanceMarket
AdvanceAcheivements
