### ISSUE TITLE
Plugin being Disabled at reboot. 

### ISSUE THREAD

**Issue by souldin** [ConnorLinfoot/CratesPlus#718]
The plugin has been working with no issues, and all the sudden i am getting issues and it is being disabled. I am Running Paper 1.14.4. I am lost on the error has it is giving org.bukkit.Location.getBlock and that just does not add up to me. 

[18:36:11] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.2 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.4.jar:git-Paper-225]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[18:36:11] [Server thread/INFO]: [CratesPlus] Disabling CratesPlus v4.5.2

**Comment by Cylizion** [comment]
I notice you're running version PaperSpigot 225, which is not the latest build for 1.14.4. Try upgrading to PaperSpigot 230 and see if that fixes your issue.

**Comment by souldin** [comment]
Updating did not resolve the issue. The plugin had been running fine for weeks.

**Comment by souldin** [comment]
Odd thing is i can place 1 chest down, but it breaks when a add another and restart. So if i just have 1 chest its fine but thats not what i need.
