### ISSUE TITLE
Plugin Disabled - Error while enabling.

### ISSUE THREAD

**Issue by NotTheOwner** [ConnorLinfoot/CratesPlus#727]
**Please use the issue template below. Issues not using the templates will likely be closed without warning! If you are suggesting a feature you do not need to follow the template.**

### Debug Info

N/A

### Link/paste of stack trace/error (if any)

[12:48:27] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.5.2 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.4.jar:git-Paper-238]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-238]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-238]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-238]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-238]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-238]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[12:48:27] [Server thread/INFO]: [CratesPlus] Disabling CratesPlus v4.5.2

### Actions to reproduce (if known):
Starting the server with plugin and PerWorldPlugin installed - i need this plugin or something like it due to the fact i run a one server Multiverse with a lot of plugins - 130 plugins enabled.

**Comment by ChrusKosco** [comment]
I have some type of same problem does not load when server restarts and to reload everytime it
restarts *FIX PLZ*
