### ISSUE TITLE
Error occurred while enabling CratesPlus v4.5.3 (Is it up to date?)

### ISSUE THREAD

**Issue by rafahsilva** [ConnorLinfoot/CratesPlus#775]
> [18:14:43 INFO]: [CratesPlus] Enabling CratesPlus v4.5.3
> [18:14:43 ERROR]: Error occurred while enabling CratesPlus v4.5.3 (Is it up to date?)
java.lang.NullPointerException
at org.bukkit.Location.getBlock(Location.java:87) ~[server.jar:git-PaperSpigot-"4c7641d"]
at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [18:14:43 INFO]: [CratesPlus] Disabling CratesPlus v4.5

Obs: Estou usando PaperSpigot na 1.8.8, quando uso o plugin plugman com o comando "/plugman reload CratesPlus" o plugin volta a funcionar e quando reinicio o servidor ele da esse erro e não funciona.

**Comment by ben4561** [comment]
I had the same problem, the way i fixed it was by copying my config.yml and then deleting the CratesPlus folder, i then started the server back up to let the CratesPlus folder regenerate and then pasted my config.yml back in. I also would not recommend using Plugman and what Minecraft version are you using for your server?
