### ISSUE TITLE
Percentage Error

### ISSUE THREAD

**Issue by Byakkoki** [ConnorLinfoot/CratesPlus#786]
Hey ! (Im French sorry for my translation)

I have a problem since yesterday I can no longer put a percentage on crate while two weeks ago this system worked great!
Here is the error code I get when I try to put percentage on my crates:
PS: my version MC is 1.7.10

[22:29:57 ERROR]: Cannot load plugins/CratesPlus/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character         '\t' that cannot start any token
 in "<string>", line 46, column 1:
        Percentage: 25
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[YamlConfiguration.class:1.7.10-1614.57]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[FileConfiguration.class:1.7.10-1614.57]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[FileConfiguration.class:1.7.10-1614.57]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [YamlConfiguration.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:183) [JavaPlugin.class:1.7.10-1614.57]
        at plus.crates.CratesPlus.reloadPlugin(CratesPlus.java:400) [CratesPlus-4.5.2.jar:?]
        at plus.crates.Commands.CrateCommand.onCommand(CrateCommand.java:196) [CratesPlus-4.5.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.57]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token; found character      '\t' that cannot start any token
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[ScannerImpl.class:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179) ~[ScannerImpl.class:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563) ~[ParserImpl$ParseBlockMappingKey.class:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[ParserImpl.class:?]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146) ~[ParserImpl.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123) ~[Composer.class:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106) ~[Composer.class:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121) ~[BaseConstructor.class:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480) ~[Yaml.class:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:399) ~[Yaml.class:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[YamlConfiguration.class:1.7.10-1614.57]
        ... 20 more

**Comment by ConnorLinfoot** [comment]
Something is wrong with your config. There is no reason for this to be an issue with the plugin if it randomly started occuring.
