### ISSUE TITLE
Error (1.16.1)

### ISSUE THREAD

**Issue by KamilM3004** [ConnorLinfoot/CratesPlus#791]
[21:21:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.2
java.lang.NullPointerException: null
	at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:45) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[survival1-16-x.jar:git-Paper-138]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[survival1-16-x.jar:git-Paper-138]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[survival1-16-x.jar:git-Paper-138]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[survival1-16-x.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1454) ~[?:git-Paper-138]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1266) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[survival1-16-x.jar:git-Paper-138]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[survival1-16-x.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by KamilM3004** [comment]
Its constantly spam my console

**Comment by ConnorLinfoot** [comment]
Should be fixed in the next update soon #793
