### ISSUE TITLE
magma server-minecraft 1.12.2-pixelmon or offline server dontworks

### ISSUE THREAD

**Issue by erposse90** [ConnorLinfoot/CratesPlus#806]
hi,until recently I was using the plugin quietly, then it started not working .. previe, left click, works, while using crate, right click, no, opens the chest normally with and without key ..
since the change of operation I have made only two changes to the server, the first is that it is now in offline mode, sp user, the second is that I tried to create a crate that used a command from the pixelmon mod. unfortunately things have been brought together and I don't know if before the pixelmon command it worked or not, after the switch to offline.
however this is the error:

25.12 01:17:57 [Server] Server thread/ERROR [Minecraft]: Could not pass event PlayerInteractEvent to CratesPlus v4.5.3
25.12 01:17:57 [Server] INFO  org.bukkit.event.EventException: null
25.12 01:17:57 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:81f47df]
25.12 01:17:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:81f47df]
25.12 01:17:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:81f47df]
25.12 01:17:57 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:263) [CraftEventFactory.class:81f47df]
25.12 01:17:57 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:479) [or.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1139) [pa.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
25.12 01:17:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
25.12 01:17:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
25.12 01:17:57 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924) [MinecraftServer.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
25.12 01:17:57 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
25.12 01:17:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
25.12 01:17:57 [Server] INFO Caused by: java.lang.NullPointerException
25.12 01:17:57 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:221) ~[CraftHumanEntity.class:81f47df]
25.12 01:17:57 [Server] INFO at plus.crates.Opener.BasicGUIOpener.doReopen(BasicGUIOpener.java:141) ~[?:?]
25.12 01:17:57 [Server] INFO at plus.crates.Listeners.PlayerInteract.onPlayerInteract(PlayerInteract.java:80) ~[?:?]
25.12 01:17:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor135.execute(Unknown Source) ~[?:?]
25.12 01:17:57 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:81f47df]
25.12 01:17:57 [Server] INFO ... 16 more

**Comment by erposse90** [comment]
ok, it was the pixelmon command that broke the plugin ..
reloading all the settings it worked again even in offline mode
